### ISSUE TITLE
Syslog-ng TLS server: no shared cipher

### ISSUE THREAD

**Issue by Viaguld** [balabit/syslog-ng#942]
Hello!
I attempted to create a secure logging system with mutual authentication using syslog-ng 3.7.2 in gentoo according to these manuals for [client](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/procedure-configuring-mutual-tls-client.html) and for [server](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/procedure-configuring-mutual-tls-client.html). The problem is when client tries to connect to server the server drops the connection with the **tls_error='SSL routines:ssl3_get_client_hello:no shared cipher'** and the client reports that handshake failed and closes the connection, however when using bare openssl in s_server and s_client mode with same configuration the connection establishes successfully. Also when I try to connect syslog-ng client to openssl s_server it`s working and openssl accepts connection, but when I try to connect openssl s_client to syslog-ng server, it fails with the same error (SSL routines:ssl3_get_client_hello:no shared cipher).

This is configuration for server:

```
@version: 3.7
@include "scl.conf"

options {
        threaded(yes);
        chain_hostnames(no);
        stats_freq(43200);
        mark_freq(3600);
        use-dns(yes);
        keep-hostname(yes);
        use-uniqid(yes);
};

source s_system {
        system();
};
source s_internal {
        internal();
};

source s_net {
        syslog(
                ip("10.0.1.7")
                port("6514")
                transport("tls")
                tls(
                        peer-verify(required-trusted)
                        ca-dir('/etc/syslog-ng/keys/ca.d')
                        key-file('/etc/syslog-ng/keys/server.key')
                        cert-file('/etc/syslog-ng/keys/server.crt')
                        trusted-dn("C=UA,O=COMPANY,OU=SERVERS,CN=*,title=SYSLOG")
                ));
};

destination d_file {
        file("/var/log/messages");
};

log {
        source(s_system);
        source(s_internal);
        source(s_net);
        destination(d_file);
};
```

This is configuration for client:

```
@version: 3.7
@include "scl.conf"

options {
        threaded(yes);
        chain_hostnames(no);
        stats_freq(43200);
        mark_freq(3600);
        use-dns(yes);
        keep-hostname(yes);
        use-uniqid(yes);

};

source src {
        internal();
};

destination messages {
                file("/var/log/messages");
};

destination d_network {
        syslog(
                "10.0.1.7"
                port("6514")
                transport("tls")
                tls(
                        ca-dir('/etc/syslog-ng/keys/ca.d')
                        key-file('/etc/syslog-ng/keys/server.key')
                        cert-file('/etc/syslog-ng/keys/server.crt')
                )
        );
};

log {
        source(src);
        destination(d_network);
        destination(messages);
};
```

**Comment by bazsi** [comment]
syslog-ng creates the SSL context with SSL_OP_NO_SSLv2 option, which means
that it is equivalent to using openssl s_client with the -nossl2 option.

-- 
Bazsi

**Comment by dksat** [comment]
After several attempts to connect to syslog-ng server with openssl s_client with command ` openssl s_client -no_ssl2 -no_ssl3 -connect 10.0.1.7:6514 -cert server.crt -key server.key -CApath ca.d -state -status` I still get the same error.
```
Feb 20 18:05:36 logs syslog-ng[9639]: Syslog connection accepted; fd='16', client='AF_INET(10.0.1.6:58015)', local='AF_INET(10.0.1.7:6514)'
Feb 20 18:05:36 logs syslog-ng[9639]: SSL error while reading stream; tls_error='SSL routines:ssl3_get_client_hello:no shared cipher'
Feb 20 18:05:36 logs syslog-ng[9639]: I/O error occurred while reading; fd='16', error='Connection reset by peer (104)'
Feb 20 18:05:36 logs syslog-ng[9639]: Syslog connection closed; fd='16', client='AF_INET(10.0.1.6:58015)', local='AF_INET(10.0.1.7:6514)'
```
s_client produces next output:

```
CONNECTED(00000003)
SSL_connect:before/connect initialization
SSL_connect:SSLv2/v3 write client hello A
SSL3 alert read:fatal:handshake failure
SSL_connect:error in SSLv2/v3 read server hello A
128491350390416:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 327 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1455999630
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
SSL3 alert write:warning:close notify
```
Also I have tried explicitly set SSL version in s_client:
 `openssl s_client -no_ssl2 -ssl3 -connect 10.0.1.7:6514 -cert server.crt -key server.key -CApath ca.d -state -status`
`openssl s_client -no_ssl2 -tls1 -connect 10.0.1.7:6514 -cert server.crt -key server.key -CApath ca.d -state -status`
`openssl s_client -no_ssl2 -tls1_1 -connect 10.0.1.7:6514 -cert server.crt -key server.key -CApath ca.d -state -status`
with same effect of server cant find shared ciphers and handshake failure on client side.

P.S. OpenSSL version is 1.0.2f

**Comment by pasztor** [comment]
@bazsi I can confirm, there is a bug there, how we initialize the ssl context on server side.
I already found that on Friday, I just did not wrote the issue to github yet.
Now, the issue is already here.
The only difference is that, if I did not specify any cipher-suite, then it worked in my case.
But most of the ciphers, what we support or is in our docs is not working.

(BTW, I found a nicer way to enlist the ciphers, what we can use in the cipher-suite: I already send to the doc team these partial-results, what I found during my investigation.)

When I tested the working, I used the semi-official osb-build, what @lbudai did.
So, on debian/ubuntu I could use mutual authentication, just the cipher-suite what can be enforced is much shorter. I write this from my own laptop, so I do not see my internal notes, but there are ciphers which worked in my case.

If sy give me a helping hand on monday, I gladly hunt down, where the bug is.

**Comment by bazsi** [comment]
Hi,

I tried to reproduce the issue on my Ubuntu box:

ii  openssl                                     1.0.2d-0ubuntu1.3
amd64                      Secure Sockets Layer toolkit - cryptographic
utility

And it seems to work properly. At least the handshake succeeded. I don't
know what @pasztor has found, but this config worked for me:

I modified yours just to make it sane in my local environment:

source s_network {
        network(
                #ip("10.0.1.7")
                port("6514")
                transport("tls")
                tls(
                        peer-verify(required-trusted)
                        ca-dir('etc/keys/ca.d')
                        key-file('etc/keys/server.key')
                        cert-file('etc/keys/server.crt')

##trusted-dn("C=UA,O=COMPANY,OU=SERVERS,CN=*,title=SYSLOG")
                ));
};

CONNECTED(00000003)
SSL_connect:before/connect initialization
SSL_connect:SSLv2/v3 write client hello A
OCSP response: no response sent
SSL_connect:unknown state
depth=1 C = HU, ST = Budapest, O = syslog-ng demo, OU = syslog-ng demo, CN
= syslog-ng demo CA
verify return:1
depth=0 C = HU, ST = Budapest, L = Budapest, O = syslog-ng demo, OU =
syslog-ng demo, CN = localhost
verify return:1
SSL_connect:unknown state
SSL_connect:unknown state
SSL_connect:unknown state
SSL_connect:unknown state
SSL_connect:unknown state
SSL_connect:unknown state
SSL_connect:unknown state
SSL_connect:unknown state
SSL_connect:unknown state
SSL_connect:unknown state
SSL_connect:unknown state
---
Certificate chain
 0 s:/C=HU/ST=Budapest/L=Budapest/O=syslog-ng demo/OU=syslog-ng
demo/CN=localhost
   i:/C=HU/ST=Budapest/O=syslog-ng demo/OU=syslog-ng demo/CN=syslog-ng demo
CA
 1 s:/C=HU/ST=Budapest/O=syslog-ng demo/OU=syslog-ng demo/CN=syslog-ng demo
CA
   i:/C=HU/ST=Budapest/O=syslog-ng demo/OU=syslog-ng demo/CN=syslog-ng demo
CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIID5TCCAs2gAwIBAgIJAPVdxIom9LGYMA0GCSqGSIb3DQEBCwUAMG4xCzAJBgNV
BAYTAkhVMREwDwYDVQQIDAhCdWRhcGVzdDEXMBUGA1UECgwOc3lzbG9nLW5nIGRl
bW8xFzAVBgNVBAsMDnN5c2xvZy1uZyBkZW1vMRowGAYDVQQDDBFzeXNsb2ctbmcg
ZGVtbyBDQTAeFw0xNjAyMjEwNjQ1NTFaFw0xNzAyMjAwNjQ1NTFaMHkxCzAJBgNV
BAYTAkhVMREwDwYDVQQIDAhCdWRhcGVzdDERMA8GA1UEBwwIQnVkYXBlc3QxFzAV
BgNVBAoMDnN5c2xvZy1uZyBkZW1vMRcwFQYDVQQLDA5zeXNsb2ctbmcgZGVtbzES
MBAGA1UEAwwJbG9jYWxob3N0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
AQEAo5Z4nJmWuaY0XY23bUe5jRfqRQAgSQZmcRM7wppRnSTIJg6D/e/E5z9rN/+m
AKR8FcqYHqCZnotMOJBdOQvWromI1H/80lh1GGZyOMWiowna6npUFx36QlgxTytc
TWhgmG+xVOmmKxglIase9Uv7m1bkmUBeZBuc4oFtO6owhBPocKISO/aUR5uG4lhQ
XkcofziaC+L28mHMmqrix8B8V10/ET1B1h8DPoR0kYYU8AKoHkrSOI5R1dr6ODn5
w5Vuyzyyl0dmuPLzoYsRypCkqPGhNlVuGWmVvcBetJy2k2VPXS5KL8Tz6iKp4AMy
ETBTwaLA38LRa2SEuXUG9PqsdQIDAQABo3sweTAJBgNVHRMEAjAAMCwGCWCGSAGG
+EIBDQQfFh1PcGVuU1NMIEdlbmVyYXRlZCBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQU
T5C0Rdv0dZTD+GlOofP6vC9TcUYwHwYDVR0jBBgwFoAUMdf5vIeoCfPxL4Rdw4aK
f7rkgN8wDQYJKoZIhvcNAQELBQADggEBAFJIz/Zk8Jp6zDaqnnVI29gNrfadNmFv
ueuNpLTaP7PotAmcQ68V2vCCVSIDZhZ7ga8GcWSI2z3TDznkRxOOEMggAW4izai4
5gigbYnCfibu4vmCiJPwmHMgJprx5z7gvzCqG9L1HmUTtnQMExTGIC71S0OWbe+K
FoaQjZDmgMAzYtwGqG5sAAoCLYgg2GVcI2QeOP6A01dBuWUmNrNTZNUSisQUVQMx
HYN8uembj4aBtLWBIHMWgT6hKdgeDRQ4AKrx97c5ErWcmaMhRms148y1mnPioOXz
iPNACTYvMEYj6b1JyJTxc9yPNSQQ22eD3vK58J8X1evQTiN/AaboHgU=
-----END CERTIFICATE-----
subject=/C=HU/ST=Budapest/L=Budapest/O=syslog-ng demo/OU=syslog-ng
demo/CN=localhost
issuer=/C=HU/ST=Budapest/O=syslog-ng demo/OU=syslog-ng demo/CN=syslog-ng
demo CA
---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms:
RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224:RSA+SHA1:DSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms:
RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224:RSA+SHA1:DSA+SHA1:ECDSA+SHA1
---
SSL handshake has read 3314 bytes and written 2877 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-GCM-SHA384
    Session-ID:
336F333CA34E7CDAB061A398C9E772B779BBDB5D0DAA5B055791122B53EA0802
    Session-ID-ctx:
    Master-Key:
5279E8ABEB39C614228A11B16C44E12FDF270AD54C6FCBED8BE623001540DB5111C825576A144CA9D371DAFFF9197FF4
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 5e de a2 fb b6 ba d4 57-44 10 6a 2c c0 87 d9 22
^......WD.j,..."
    0010 - 0a 61 be ca f2 fa f5 c7-dc d4 1e e4 da 02 34 db
.a............4.
    0020 - 9d fb 49 a5 46 9c 92 b9-48 a3 a0 ff 95 b7 1b d2
..I.F...H.......
    0030 - d0 fa 1b ad 60 a9 e8 b5-b2 3a d9 30 bf 4c f2 db
....`....:.0.L..
    0040 - cd 9a 5a 78 52 a3 0b 54-27 b1 d3 ea 4f 40 37 ac
..ZxR..T'...O@7.
    0050 - 65 18 df 9c a7 bb 04 ca-21 b2 43 29 69 75 e7 4c
e.......!.C)iu.L
    0060 - 80 a2 7d 5f f6 7c c3 7a-ff 90 47 8b 00 43 61 ef
..}_.|.z..G..Ca.
    0070 - d3 43 79 90 68 c1 40 f1-e5 ee e6 be 1a 92 c7 c1   .Cy.h.@
.........
    0080 - d9 56 4f f6 48 85 a3 26-26 9e 75 5f 37 22 1d 97
.VO.H..&&.u_7"..
    0090 - 3e cf 17 94 02 42 71 82-2f 29 37 e6 0c f4 5e 8f
>....Bq./)7...^.
    00a0 - 90 7f 79 c1 af 7f 08 76-aa b6 fc 6b 1c d7 aa 87
..y....v...k....
    00b0 - 99 a4 9d 88 77 0c 00 a6-c7 6c 2c 5f b1 59 73 f9
....w....l,_.Ys.
    00c0 - cf 03 28 4f 31 54 ab 0c-9c 30 0e f3 44 6b 3e 1d
..(O1T...0..Dk>.
    00d0 - 97 a5 5a 45 d8 7a c3 e6-59 3d 67 29 c0 90 3e 94
..ZE.z..Y=g)..>.
    00e0 - b1 dc 57 fd a7 ac 91 70-2d 94 b0 2c 41 4e 37 00
..W....p-..,AN7.
    00f0 - 9b 6c d0 04 84 33 04 62-cf 0c 0b 4b b0 36 21 7e
.l...3.b...K.6!~
    0100 - b9 9e 75 02 51 e9 f1 ef-f7 c5 5a 22 c5 b7 e0 5c
..u.Q.....Z"...\
    0110 - a7 29 4f d0 62 c9 48 32-39 07 cf 56 97 8c c2 e4
.)O.b.H29..V....
    0120 - d8 eb 23 14 4c e3 cb 59-7d 55 a6 bd e3 f8 5a e7
..#.L..Y}U....Z.
    0130 - 2d 79 8e c2 91 89 a1 51-9d 79 3b 20 27 30 34 cf   -y.....Q.y;
'04.
    0140 - a2 e5 68 0d bd 68 84 2e-3d 2f db 84 c0 20 d3 9b   ..h..h..=/...
..
    0150 - ff eb 79 ce 9f 1e 8f bb-20 04 61 09 20 83 0d 02   ..y..... .a.
...
    0160 - 4b 9c a3 a6 41 86 f0 08-a1 ae ef 28 3d 56 87 ef
K...A......(=V..
    0170 - cc fb d0 8f cf c5 db bd-96 8a 38 0f b0 29 9a 03
..........8..)..
    0180 - 3c fb f1 09 f5 95 90 60-b5 12 22 c5 f7 a2 ba b6
<......`..".....
    0190 - 5f 52 de 1d 18 42 4c 16-5f 44 02 67 72 bc 55 e6
_R...BL._D.gr.U.
    01a0 - 23 22 00 d8 9a 42 8a 5d-d7 df 46 3d f3 62 cb 1c
#"...B.]..F=.b..
    01b0 - 0f cd f5 ed b0 a5 fe 45-ec 71 42 a4 79 b1 76 de
.......E.qB.y.v.
    01c0 - 1e e4 e1 5b 6b e1 12 e6-b2 9b 83 26 6d dc 1a 4d
...[k......&m..M
    01d0 - 79 49 87 24 a3 84 7a 58-ba ec 9b d4 65 54 95 56
yI.$..zX....eT.V
    01e0 - ae e7 7e ad f2 95 d9 e8-f0 5c d4 84 29 e7 2d 91
..~......\..).-.
    01f0 - 02 57 13 67 e2 cb ce 2b-6d 6c e3 c1 9e 23 e1 07
.W.g...+ml...#..
    0200 - 0c 95 b8 96 49 9c 00 5b-53 0d 18 bf f0 90 ec 88
....I..[S.......
    0210 - ee 36 7f 29 4b 2f 19 cb-52 de a3 8b 64 e1 8d 1a
.6.)K/..R...d...
    0220 - 93 9c 51 8d 87 7a 6b b4-29 87 5d d8 f7 13 cb 58
..Q..zk.).]....X
    0230 - df f5 54 e3 f6 06 15 49-d2 48 6e 4f d9 76 5a c6
..T....I.HnO.vZ.
    0240 - b9 b8 e1 56 da 8f 93 8b-24 ad bd 8c 8c 41 dd 00
...V....$....A..
    0250 - 5d 5d 91 53 2a f9 fe f1-45 78 ff 4c ef 59 b7 e7
]].S*...Ex.L.Y..
    0260 - 16 ce 19 cb 87 02 fd 89-64 31 3e 2d 65 32 e8 13
........d1>-e2..
    0270 - 5f 3c 28 0d 5c 79 e8 c6-c6 43 74 eb f8 98 d9 1f
_<(.\y...Ct.....
    0280 - 6c 6b ce 60 17 a1 07 6a-c2 a4 22 62 e8 6f fb 61
lk.`...j.."b.o.a
    0290 - bb da d7 87 77 b9 02 f1-77 87 91 45 b7 ae 02 3b
....w...w..E...;
    02a0 - 9d 3a ba 28 a3 df 60 f1-c4 27 b8 25 55 31 06 9e
.:.(..`..'.%U1..
    02b0 - 8c 6e 82 de 25 2f 56 04-2b 38 58 45 3a d8 2e 7a
.n..%/V.+8XE:..z
    02c0 - 10 83 f7 c0 7a 70 e0 63-e4 9f 02 8d 2c e7 61 e4
....zp.c....,.a.
    02d0 - 4c af c3 43 12 6c 93 e2-12 9b 15 97 8c 66 de c9
L..C.l.......f..
    02e0 - ae a7 56 d2 0d d1 17 86-d4 e5 1c de 34 4a 0a 3d
..V.........4J.=
    02f0 - af 03 7f 1f db 47 5f 42-08 0a bd 77 52 fb a0 23
.....G_B...wR..#
    0300 - ab 40 09 a0 23 ed 03 24-06 f9 c1 11 33 f5 ce 79
.@..#..$....3..y
    0310 - 98 1b d5 72 5b 4d b2 ca-43 46 40 da dc 24 29 da   ...r[M..CF@
..$).
    0320 - d3 76 d4 7a e9 47 8d 14-ea e0 e6 37 ff e8 31 2c
.v.z.G.....7..1,
    0330 - 21 84 2e b3 1e 01 d3 0b-ce fe 9a fe 9f a0 b7 5b
!..............[
    0340 - 73 40 5c af 51 60 34 0d-c7 14 7a 2d cb 0e e6 f0   s@
\.Q`4...z-....
    0350 - 9b 45 aa 8a f9 1d 87 fd-3c be 9a a6 8a 8f 5b d4
.E......<.....[.
    0360 - 17 3c 7c 03 ec d2 40 14-f2 98 2c 8d 69 28 9f 94
.<|...@...,.i(..
    0370 - ff 82 ac 02 41 50 9a b3-bc 51 01 d5 64 e0 70 1f
....AP...Q..d.p.
    0380 - 57 87 74 3e 77 42 ad c2-85 14 03 c2 d2 73 0d c5
W.t>wB.......s..
    0390 - f9 7c d3 c6 90 b1 35 e6-9d ca 9d 91 ca 65 b0 3d
.|....5......e.=
    03a0 - de 52 3e 13 4c 8d 73 3d-df cb 48 7c 73 54 9b a8
.R>.L.s=..H|sT..
    03b0 - 9c 0f 3a e6 dc 1b 4e 80-f7 e1 77 c3 07 73 a1 d6
..:...N...w..s..
    03c0 - dc fe f3 15 e3 00 77 60-34 13 a5 f7 45 37 8d d3
......w`4...E7..
    03d0 - d7 eb 8b 17 26 63 05 f3-7d 89 24 d4 37 99 c4 08
....&c..}.$.7...
    03e0 - b3 85 6d fc b1 92 a0 76-fa 6b ba 9c 96 46 4e ba
..m....v.k...FN.
    03f0 - 09 b9 16 88 5a 6e d2 a5-ed ee 40 9a 5c a7 fa 4f   ....Zn....@
.\..O
    0400 - 2b d3 d4 51 c7 b6 ad 02-15 63 1e 80 ba f5 eb 62
+..Q.....c.....b
    0410 - 6b ab 77 5d 3b 94 88 82-ed 98 2a 56 7c 50 b9 56
k.w];.....*V|P.V
    0420 - 94 9b 15 2a da 9b 61 df-fd 30 e7 b4 6c 49 95 e6
...*..a..0..lI..
    0430 - 67 d4 02 ce 66 00 dd f3-21 a2 86 0f 7e 65 6e a6
g...f...!...~en.
    0440 - 63 72 45 73 6f 5b ef ce-fd 0c 53 ee cc f0 cb 4a
crEso[....S....J
    0450 - ed 32 8d f0 db a4 a9 b6-dd cf af 7a 6f cb 0e 4e
.2.........zo..N
    0460 - 4f 73 5c 1b 10 4b c9 6a-57 66 6f 38 f4 8d 8c f0
Os\..K.jWfo8....
    0470 - 4a a6 c0 bf 31 a3 ee e7-c0 56 90 1e a2 c9 c4 39
J...1....V.....9
    0480 - df df c9 47 6d dd b0 9c-d5 61 fa 60 36 dd 2f fc
...Gm....a.`6./.

    Start Time: 1456037867
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---


-- 
Bazsi

**Comment by pasztor** [comment]
@bazsi as I said, the problem what I found:
Many of the ciphers do not work, which are in our docs.
If you do not restrict the ciphers, then it works.
(I think, vven the "default" setting, which are in our docs are not really punctual.)
Or if you choose a "good" cipher, then it also works.
But many of the ciphers do not work.

Eg. ciphers-suite(AES256-GCM-SHA384) works.
This was, practically the only one TLSv1.2 supported cipher, which appeared only in TLSv1.2 and not sooner in the protocol, and I achieved to work.
However, I found many other which do not: I tried the first 2-3-4 from our docs. I do not remember exactly. The did not worked.
Then I did not create a restriction on server side. And connected with s_client, but -nossl2 -nossl3 -notls1 -notls1_1.
Then the client and the server agreed in AES256-GCM-SHA384.
So, yes I can confirm, that AES256-GCM-SHA384 can work.
This ose doc do not contain a list:
https://www.balabit.com/documents/syslog-ng-ose-3.7-guides/en/syslog-ng-ose-guide-admin/html/tlsoptions.html#tls-options-cipher-suite
So, I tried this list:
https://www.balabit.com/documents/syslog-ng-pe-5.0-guides/en/syslog-ng-pe-guide-admin/html/tlsoptions.html#idp10622640
I tested some ECDHE and some DHE cipher suites too. None of them worked.

**Comment by bazsi** [comment]
But in this ticket no explicit cipher suite was specified.

**Comment by dksat** [comment]
After I had changed my keys and certificates from EC to RSA and set `ciphers-suite(AES256-GCM-SHA384)` , SSL connection begun to work.

**Comment by dksat** [comment]
oops, sorry I pressed the wrong the button...

**Comment by lbudai** [comment]
hmm.. it seems that I also closed this bug, but I _didn't_ ...

**Comment by MrAnno** [comment]
Hello,

As I see, elliptic curve and Diffie-Hellman based ciphers are not working with syslog-ng at the moment. To support these ciphers, we should set up DH parameters and EC keys (`SSL_CTX_set_tmp_dh` and `SSL_CTX_set_tmp_ecdh`).

Is it a bad idea to make these parameters configurable (the curve name and DH params file) in syslog-ng.conf?

**Comment by bazsi** [comment]
It would be a great idea. (they are both Diffie-Hellman parameters though,
but the first is the "traditional" DH, the 2nd is part of elliptic curve
cryptography).


-- 
Bazsi

**Comment by MrAnno** [comment]
(Sorry for my confusion.)
What do you think about `dh-file()` and `ecparam-name()` as TLS options?

Example configuration:
```
source s_tls {
	syslog(
		port(1999)
		transport("tls")
		tls(
			peer-verify(required-trusted)
			ssl-options("no-sslv2")
			ca-dir("/home/mranno/tls/ca.d/")
			key-file("/home/mranno/tls/serverkey.pem")
			cert-file("/home/mranno/tls/servercert.pem")

			#dh-file("/home/mranno/tls/dh2048.pem")
			#ecparam-name("prime256v1")
		)
	);
};
```

**Comment by bazsi** [comment]
we should use a bit more consistency.

dh-file() - for specifying a file that contains this
dh-group() - for specifying DH group by name
ecdh-curve() -



-- 
Bazsi

**Comment by pasztor** [comment]
Since this is an enhancement, and considering that enlisting the EC and DH ciphers is a bug, I suggest the following:
change our cipher-suite("DEFAULT") default to ciphers-suite("DEFAULT:-ECDH:-DH:-SRP")
so, if someone want to allow these ciphers, S/he must change these behaviour explicitly.
One more thing: If I param openssl s_server and gave eg. ECDHE-RSA-AES256-GCM-SHA384 as cipher on the client side, it also works.
So the dh-file(), dh-group(), ecdh-curve() can provide some default-working behaviour, like openssl s_server has, but it also need user act to allow these ciphers.
So, if somebody read the docs, and change cipher-suite to "DEFAULT" (to openssl's default cipher list) he could allow ecdh and dh ciphers with this step, and it would work out of the box.
It can serve the "user" as a first approach test.
Then as a second step S/he could continue setting up syslog-ng to generate her/his own EC and DH parameters.

My .02€

**Comment by pasztor** [comment]
One more thing I noticed, when I checked cipher-suite() settings:
SRP-* ciphers are not working either.

BTW.: I think, doc should be also contain example, that cipher-suite() can contain any string, what we can define to openssl ciphers command as it's argument, and it limit / set the available ciphers in the same way as openssl ciphers command enlist them. Also a link to man ciphers there would be also a good idea. Eg. this link in the online version: https://www.openssl.org/docs/manmaster/apps/ciphers.html and man link to ciphers in the man version.

BTW: SRP / -SRP is also not listed in ciphers man page, nor in the online master version's link, I wrote above. I have just found it based on a gut-feeling. (At least it has it's own consistency too.)

**Comment by pasztor** [comment]
Okay, I investigated it a bit more:
So, now the openssl's list is this:
pgyorgy@enterprise:~$ openssl ciphers -v DEFAULT:-ECDH:-DH:-SRP
AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
AES256-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA256
AES256-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA1
CAMELLIA256-SHA         SSLv3 Kx=RSA      Au=RSA  Enc=Camellia(256) Mac=SHA1
PSK-AES256-CBC-SHA      SSLv3 Kx=PSK      Au=PSK  Enc=AES(256)  Mac=SHA1
DES-CBC3-SHA            SSLv3 Kx=RSA      Au=RSA  Enc=3DES(168) Mac=SHA1
PSK-3DES-EDE-CBC-SHA    SSLv3 Kx=PSK      Au=PSK  Enc=3DES(168) Mac=SHA1
AES128-GCM-SHA256       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(128) Mac=AEAD
AES128-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA256
AES128-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA1
SEED-SHA                SSLv3 Kx=RSA      Au=RSA  Enc=SEED(128) Mac=SHA1
CAMELLIA128-SHA         SSLv3 Kx=RSA      Au=RSA  Enc=Camellia(128) Mac=SHA1
PSK-AES128-CBC-SHA      SSLv3 Kx=PSK      Au=PSK  Enc=AES(128)  Mac=SHA1
RC4-SHA                 SSLv3 Kx=RSA      Au=RSA  Enc=RC4(128)  Mac=SHA1
RC4-MD5                 SSLv3 Kx=RSA      Au=RSA  Enc=RC4(128)  Mac=MD5 
PSK-RC4-SHA             SSLv3 Kx=PSK      Au=PSK  Enc=RC4(128)  Mac=SHA1
DES-CBC-SHA             SSLv3 Kx=RSA      Au=RSA  Enc=DES(56)   Mac=SHA1
----
It contains PSK ciphers too.
I think psk needs the preshared key also as a separate configuration option, if we want it to work.
(Since they do not work)
So, I suggest as default this setting:
pgyorgy@enterprise:~$ openssl ciphers -v DEFAULT:-ECDH:-DH:-SRP:-PSK
AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
AES256-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA256
AES256-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA1
CAMELLIA256-SHA         SSLv3 Kx=RSA      Au=RSA  Enc=Camellia(256) Mac=SHA1
DES-CBC3-SHA            SSLv3 Kx=RSA      Au=RSA  Enc=3DES(168) Mac=SHA1
AES128-GCM-SHA256       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(128) Mac=AEAD
AES128-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA256
AES128-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA1
SEED-SHA                SSLv3 Kx=RSA      Au=RSA  Enc=SEED(128) Mac=SHA1
CAMELLIA128-SHA         SSLv3 Kx=RSA      Au=RSA  Enc=Camellia(128) Mac=SHA1
RC4-SHA                 SSLv3 Kx=RSA      Au=RSA  Enc=RC4(128)  Mac=SHA1
RC4-MD5                 SSLv3 Kx=RSA      Au=RSA  Enc=RC4(128)  Mac=MD5 
DES-CBC-SHA             SSLv3 Kx=RSA      Au=RSA  Enc=DES(56)   Mac=SHA1

I tested the connection between two syslog-ng. On the server I did not specify any cipher-suite(), only on the client side. All element of this list worked well.

However, RC4, and DES are pretty week.

Or, if we want a really great default, another suggestion can be this:
pgyorgy@enterprise:~$ openssl ciphers -v DEFAULT:-ECDH:-DH:-SRP:-PSK:-LOW:-MEDIUM
AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
AES256-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA256
AES256-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA1
CAMELLIA256-SHA         SSLv3 Kx=RSA      Au=RSA  Enc=Camellia(256) Mac=SHA1
DES-CBC3-SHA            SSLv3 Kx=RSA      Au=RSA  Enc=3DES(168) Mac=SHA1
AES128-GCM-SHA256       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(128) Mac=AEAD
AES128-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA256
AES128-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA1
CAMELLIA128-SHA         SSLv3 Kx=RSA      Au=RSA  Enc=Camellia(128) Mac=SHA1

**Comment by MrAnno** [comment]
> One more thing: If I param openssl s_server and gave eg. ECDHE-RSA-AES256-GCM-SHA384 as cipher on the client side, it also works.
> So the dh-file(), dh-group(), ecdh-curve() can provide some default-working behaviour, like openssl s_server has, but it also need user act to allow these ciphers.

We can set up hard-coded fallback parameters if the user does not specify them explicitly ([OpenSSH is doing the same](https://github.com/openssh/openssh-portable/blob/master/dh.c#L351)).

Also, in OpenSSL s_server: https://github.com/openssl/openssl/blob/master/apps/s_server.c#L1887
(but I am afraid `SSL_CTX_set_dh_auto` is not documented)

**Comment by ouarak** [comment]
Hi Everyone,
what was the outcome of this discussion? how can i restrict ciphers on the syslog-ng to be just 
•	TLS_RSA_WITH_AES_128_CBC_SHA 
•	TLS_RSA_WITH_AES_128_CBC_SHA256 
•	TLS_RSA_WITH_AES_256_CBC_ SHA256 
•	TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 
•	TLS_DHE_RSA_WITH_AES_128_CBC_SHA256

thank you very much for your help.
Fa

**Comment by MrAnno** [comment]
Hi,

Currently DH-based ciphers (DH, DHE, ECDH, ECDHE) are not working in syslog-ng OSE.
We have implemented this feature in syslog-ng Premium Edition 6, but it hasn't been backported to OSE yet.

I'm planning to reimplement those patches in the near future, I'll let you know when it is ready.

You can restrict ciphers in your syslog-ng.conf configuration file with the [cipher-suite()](https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/tlsoptions.html#tls-options-cipher-suite) option.

**Comment by ouarak** [comment]
thank you MrAnno for the quick replay.
what about these ciphers 👍 
.   TLS_RSA_WITH_AES_128_CBC_SHA
•	TLS_RSA_WITH_AES_128_CBC_SHA256
•	TLS_RSA_WITH_AES_256_CBC_ SHA256

I used the cipher-suite ( "AES128-SHA256: AES256-SHA256:AES-SHA") however I am still getting the same error message 👍 
Error setting up TLS session context; tls_error='SSL routines:SSL_CTX_set_cipher_list:no cipher match'

on debug mode.
could be something wrong with the syntax on the cipher-suite()

could you help

**Comment by MrAnno** [comment]
I checked it using the following config snippet:
```
    syslog(
        port(4444)
        transport(tls)
        tls (
          ca_dir("/home/anno/Work/syslog-ng/tls")
          key_file("/home/anno/Work/syslog-ng/tls/serverkey.pem")
          cert_file("/home/anno/Work/syslog-ng/tls/servercert.pem")
          cipher-suite("AES128-SHA256: AES256-SHA256:AES-SHA")
        )
    );
```

```bash
$ openssl s_client -host localhost -port 4444 -cert clientcert.pem -key clientkey.pem

...
CONNECTED(00000003)
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-SHA256
...
```

The cipher-suite you mentioned is working correctly with syslog-ng 3.9, OpenSSL 1.0.2g.

Which syslog-ng and OpenSSL versions are you using? Can you show me your config?

**Comment by ouarak** [comment]
sorry, it is my mistake, it is working now for me too.
how can i get the syslog-ng Premium Edition 6 or at least use the trial version.
thanks a lot

**Comment by MrAnno** [comment]
You can request a trial [here](https://www.balabit.com/network-security/syslog-ng/central-syslog-server/trial).
But of course, DH based cipher suites will be available in OSE as well.

**Comment by ouarak** [comment]
hi MrAnno,

I am using syslog-ng OSE and come to a problem that the trusted-dn is not behaving as I am extecting
I configured the trsuted-dn to be ("*, C=US, O=mycampny, CN=*")
however taking a look to a traffic capture is shoing the DN as empty (value 0)
everything else works fine, I am not sure if I am hitting another OSe limitation or I am doing something wrong.

would you help?
Fathi

**Comment by bazsi** [comment]
It definitely is not an ose limitation. Where do you see the zero length
string? Can you elaborate on what you see where?

Thanks

**Comment by ouarak** [comment]
hi Bazsi,

From my understanding of the "trusted-DN" section in the syslog-ng.config file is that this is the certificate_authority DN field in the TLSv1.2 handshake  message "certifucate request sent by the server". the structure of this message is described in the RFC 5246 page 53, here is a snip of it 👍 
Structure of this 
**enum {
rsa_sign(1), dss_sign(2), rsa_fixed_dh(3), dss_fixed_dh(4),
rsa_ephemeral_dh_RESERVED(5), dss_ephemeral_dh_RESERVED(6),
fortezza_dms_RESERVED(20), (255)
} ClientCertificateType;
opaque DistinguishedName<1..2^16-1>;
struct {
ClientCertificateType certificate_types<1..2^8-1>;
SignatureAndHashAlgorithm
supported_signature_algorithms<2^16-1>;
DistinguishedName certificate_authorities<0..2^16-1>;
} CertificateRequest;**


******************another snipping from page 54 same RFC*****************
the certificate_authorities
A list of the distinguished names [X501] of acceptable
certificate_authorities, represented in DER-encoded format. These
distinguished names may specify a desired distinguished name for a
root CA or for a subordinate CA; thus, this message can be used to
describe known roots as well as a desired authorization space. If
the certificate_authorities list is empty, then the client MAY
send any certificate of the appropriate ClientCertificateType,
unless there is some external arrangement to the contrary.
**********************************************************************

however taking a look to the "certificate request message record" in wireshark shows value of 0 for the DN field, so I am confused about this "trusted-DN" parameter what it is for.I was extcting to see the DN field populated with what ever i put in the "trusted-DN" parameter.
here is below a screenshot of that DN field from wireshark,

please let me know if you have question or still I am not clear on my question 

![image](https://cloud.githubusercontent.com/assets/25371619/22841235/cbe9f402-ef9e-11e6-90e4-07a6bed3b56a.png)
